### ISSUE TITLE
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: Path('')

### ISSUE THREAD

**Issue by saxyx** [FFengIll/pdf-cut-white#14]
(pythony) C:\Users\Xu\Desktop\pdf-cut-white-0.6.0\pdf-cut-white-0.6.0>python cli.py -i in.pdf -o out.pdf
2023-03-08 19:17:46.798 | WARNING  | pdf_white_cut.analyzer:extract_item_box:64 - NotImplemented and use itself: <LTTextBoxHorizontal(0) 93.122,774.467,98.642,785.507 '1\n'>
2023-03-08 19:17:46.799 | WARNING  | pdf_white_cut.analyzer:extract_item_box:64 - NotImplemented and use itself: <LTTextBoxHorizontal(1) 93.122,720.228,98.642,731.268 '3\n'>
2023-03-08 19:17:46.801 | WARNING  | pdf_white_cut.analyzer:extract_item_box:64 - NotImplemented and use itself: <LTTextBoxHorizontal(2) 93.122,665.988,98.642,677.028 '5\n'>
2023-03-08 19:17:46.802 | WARNING  | pdf_white_cut.analyzer:extract_pdf_boxs:163 - visible bbox: (93.1224, 665.9879999999999, 98.6424, 785.50704)
2023-03-08 19:17:46.803 | WARNING  | pdf_white_cut.analyzer:extract_pdf_boxs:166 - max visible bbox for the page: (93.1224, 665.9879999999999, 98.6424, 785.50704)
2023-03-08 19:17:46.804 | INFO     | pdf_white_cut.cutter:edit_pdf:56 - input file: in.pdf
2023-03-08 19:17:46.806 | INFO     | pdf_white_cut.cutter:edit_pdf:63 - origin scale: (93.1224, 665.9879999999999, 98.6424, 785.50704)
2023-03-08 19:17:46.806 | INFO     | pdf_white_cut.cutter:edit_page_box:16 - media box: RectangleObject([0, 0, 595.275574, 841.889771])
2023-03-08 19:17:46.807 | INFO     | pdf_white_cut.cutter:edit_page_box:17 - trim box: RectangleObject([0, 0, 595.275574, 841.889771])
2023-03-08 19:17:46.808 | INFO     | pdf_white_cut.cutter:edit_page_box:18 - art box: RectangleObject([0, 0, 595.275574, 841.889771])
2023-03-08 19:17:46.809 | INFO     | pdf_white_cut.cutter:edit_page_box:19 - crop box: RectangleObject([0, 0, 595.275574, 841.889771])
2023-03-08 19:17:46.810 | INFO     | pdf_white_cut.cutter:edit_page_box:20 - bleed box: RectangleObject([0, 0, 595.275574, 841.889771])
2023-03-08 19:17:46.811 | INFO     | pdf_white_cut.cutter:edit_page_box:32 - origin media box: RectangleObject([0, 0, 595.275574, 841.889771])
2023-03-08 19:17:46.815 | INFO     | pdf_white_cut.cutter:edit_page_box:37 - cut media box to: RectangleObject([93.122399999999998954081092961132526397705078125, 665.9879999999999427018337883055210113525390625, 98.6423999999999949750417727045714855194091796875, 785.50703999999996085534803569316864013671875])
2023-03-08 19:17:46.817 | ERROR    | pdf_white_cut.cutter:edit_pdf:78 - Some other Error while processing file:in.pdf
Traceback (most recent call last):

  File "C:\Users\Xu\Desktop\pdf-cut-white-0.6.0\pdf-cut-white-0.6.0\cli.py", line 15, in <module>
    edit_pdf(args.input, args.output, args.ignore)
    │        │    │      │    │       │    └ 0
    │        │    │      │    │       └ Namespace(input='in.pdf', output='out.pdf', indir='', outdir='', test=False, ignore=0, verbose=False)
    │        │    │      │    └ 'out.pdf'
    │        │    │      └ Namespace(input='in.pdf', output='out.pdf', indir='', outdir='', test=False, ignore=0, verbose=False)
    │        │    └ 'in.pdf'
    │        └ Namespace(input='in.pdf', output='out.pdf', indir='', outdir='', test=False, ignore=0, verbose=False)
    └ <function edit_pdf at 0x000001461EB144C0>

> File "C:\Users\Xu\Desktop\pdf-cut-white-0.6.0\pdf-cut-white-0.6.0\pdf_white_cut\cutter.py", line 69, in edit_pdf
    Path(target).dirname().makedirs_p()
    │    └ 'out.pdf'
    └ <class 'path.Path'>

  File "D:\anaconda3\envs\pythony\lib\site-packages\path\__init__.py", line 1168, in makedirs_p
    self.makedirs(mode)
    │    │        └ 511
    │    └ <function Path.makedirs at 0x000001461DFFE200>
    └ Path('')

  File "D:\anaconda3\envs\pythony\lib\site-packages\path\__init__.py", line 1161, in makedirs
    os.makedirs(self, mode)
    │  │        │     └ 511
    │  │        └ Path('')
    │  └ <function makedirs at 0x000001461BE4D750>
    └ <module 'os' from 'D:\\anaconda3\\envs\\pythony\\lib\\os.py'>

  File "D:\anaconda3\envs\pythony\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
    │     │     └ 511
    │     └ Path('')
    └ <built-in function mkdir>

FileNotFoundError: [WinError 3] 系统找不到指定的路径。: Path('')
2023-03-08 19:17:46.840 | ERROR    | pdf_white_cut.cutter:edit_pdf:79 - [WinError 3] 系统找不到指定的路径。: Path('')
Traceback (most recent call last):

  File "C:\Users\Xu\Desktop\pdf-cut-white-0.6.0\pdf-cut-white-0.6.0\cli.py", line 15, in <module>
    edit_pdf(args.input, args.output, args.ignore)
    │        │    │      │    │       │    └ 0
    │        │    │      │    │       └ Namespace(input='in.pdf', output='out.pdf', indir='', outdir='', test=False, ignore=0, verbose=False)
    │        │    │      │    └ 'out.pdf'
    │        │    │      └ Namespace(input='in.pdf', output='out.pdf', indir='', outdir='', test=False, ignore=0, verbose=False)
    │        │    └ 'in.pdf'
    │        └ Namespace(input='in.pdf', output='out.pdf', indir='', outdir='', test=False, ignore=0, verbose=False)
    └ <function edit_pdf at 0x000001461EB144C0>

> File "C:\Users\Xu\Desktop\pdf-cut-white-0.6.0\pdf-cut-white-0.6.0\pdf_white_cut\cutter.py", line 69, in edit_pdf
    Path(target).dirname().makedirs_p()
    │    └ 'out.pdf'
    └ <class 'path.Path'>

  File "D:\anaconda3\envs\pythony\lib\site-packages\path\__init__.py", line 1168, in makedirs_p
    self.makedirs(mode)
    │    │        └ 511
    │    └ <function Path.makedirs at 0x000001461DFFE200>
    └ Path('')

  File "D:\anaconda3\envs\pythony\lib\site-packages\path\__init__.py", line 1161, in makedirs
    os.makedirs(self, mode)
    │  │        │     └ 511
    │  │        └ Path('')
    │  └ <function makedirs at 0x000001461BE4D750>
    └ <module 'os' from 'D:\\anaconda3\\envs\\pythony\\lib\\os.py'>

  File "D:\anaconda3\envs\pythony\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
    │     │     └ 511
    │     └ Path('')
    └ <built-in function mkdir>

FileNotFoundError: [WinError 3] 系统找不到指定的路径。: Path('')

**Comment by FFengIll** [comment]
目前看是默认的输出路径问题，调整中。

**Comment by FFengIll** [comment]
#15
